name: 'Enforce PR checklist composite action'
description: 'Enforce PR checklist composite'
inputs:
  INPUT_VARIABLE:  
    description: 'Variable to use'
    required: true
    default: 'Mon code'

runs:
  using: "composite"
  steps:
    - name: Installer jq sans sudo
      run: |
        JQ_VERSION="1.6"
        JQ_BINARY="jq-linux64"
        curl -L -o jq "https://github.com/stedolan/jq/releases/download/jq-${JQ_VERSION}/${JQ_BINARY}"
        chmod +x jq
        mkdir -p $HOME/bin
        mv jq $HOME/bin/
        echo "$HOME/bin" >> $GITHUB_PATH
      shell: bash
    - name: Valider les cases cochées dans la description de la PR
      id: validate
      env: 
        GITHUB_EVENT_PATH: ${{ github.event_path }}
        
      run: |
        PR_BODY=$(jq -r '.pull_request.body' "$GITHUB_EVENT_PATH")
        
        echo $PR_BODY
        if echo "$PR_BODY" | grep -q '\- \[x\] \*\*${{ inputs.INPUT_VARIABLE }}\*\*'; then
          echo "✅ All required checkboxes are checked!" 
        else
          echo "Erreur : Certaines cases de la checklist ne sont pas cochées."
          exit 1 
        fi
      shell: bash   
    - name: Valider la description de la PR
      env:
        GITHUB_EVENT_PATH: ${{ github.event_path }}
      run: |
        PR_BODY=$(jq -r '.pull_request.body' "$GITHUB_EVENT_PATH")
        if [[ "$PR_BODY" == *"Empty"* ]]; then
          echo "The text 'Empty' exists in the PR body."
          
        else
          echo "The text 'Empty file' does not exist in the PR body."
          
        fi
      shell: bash