name: 'Parse /ci Comment'
description: 'Parse and extract parameters from /ci comments'
author: 'Michel-SG'

inputs:
  github-token:
    description: 'GitHub token for API access'
    required: false
    default: ${{ github.token }}

outputs:
  target:
    description: 'Target parameter'
    value: ${{ steps.parse-ci.outputs.TARGET }}
  version:
    description: 'Version parameter'
    value: ${{ steps.parse-ci.outputs.VERSION }}
  coverage:
    description: 'Coverage parameter'
    value: ${{ steps.parse-ci.outputs.COVERAGE }}
  parameters:
    description: 'All parameters as JSON'
    value: ${{ steps.parse-ci.outputs.parameters }}
  workflow_call_triggered:
    description: 'Whether run_ci workflow was triggered successfully'
    value: ${{ steps.trigger-workflow-call.outputs.workflow_call_triggered }}
  workflow_dispatch_triggered:
    description: 'Whether run_ci workflow (second) was triggered successfully'
    value: ${{ steps.trigger-workflow-dispatch.outputs.workflow_dispatch_triggered }}
  trigger_action_result:
    description: 'Whether trigger-action was executed successfully'
    value: ${{ steps.trigger-action.outputs.workflow_triggered }}
  trigger_action_call_result:
    description: 'Whether trigger-action-call was executed successfully'
    value: ${{ steps.trigger-action-call.outputs.workflow_triggered }}

runs:
  using: "composite"
  steps:
    - name: Parse /ci comment
      id: parse-ci
      uses: actions/github-script@v7
      with:
        github-token: ${{ inputs.github-token }}
        script: |
          try {
            const commentBody = context.payload.comment?.body || '';
            
            core.info(`📝 Commentaire reçu: ${commentBody}`);
            
            // Vérifier si le commentaire commence par /ci
            if (!commentBody.startsWith('/ci')) {
              throw new Error('Le commentaire ne commence pas par /ci');
            }
            
            core.info('✅ Commande /ci détectée');
            
            // Extraire la partie après "/ci "
            const paramsString = commentBody.substring(4).trim();
            
            if (!paramsString) {
              throw new Error('Aucun paramètre trouvé après /ci');
            }
            
            core.info(`📦 Paramètres bruts: ${paramsString}`);
            
            // Parser les paramètres
            const paramArray = paramsString
              .split(';')
              .map(p => p.trim())
              .filter(p => p);
            
            const params = {};
            let paramCount = 0;
            
            for (const param of paramArray) {
              const colonIndex = param.indexOf(':');
              
              if (colonIndex === -1) {
                core.warning(`⚠️ Format invalide pour le paramètre: ${param}`);
                continue;
              }
              
              const cleanKey = param.substring(0, colonIndex).trim().toLowerCase();
              const cleanValue = param.substring(colonIndex + 1).trim();
              
              if (!cleanKey || !cleanValue) {
                core.warning(`⚠️ Paramètre incomplet: clé="${cleanKey}", valeur="${cleanValue}"`);
                continue;
              }
              
              core.info(`✓ Paramètre trouvé: ${cleanKey} = ${cleanValue}`);
              
              params[cleanKey] = cleanValue;
              core.setOutput(cleanKey.toUpperCase(), cleanValue);
              paramCount++;
            }
            
            if (paramCount === 0) {
              throw new Error('Aucun paramètre valide trouvé');
            }
            
            core.info(`✅ ${paramCount} paramètre(s) extrait(s) avec succès`);
            core.info(`📊 Résumé: ${JSON.stringify(params)}`);
            
            // Exporter tous les paramètres en JSON
            core.setOutput('parameters', JSON.stringify(params));
            
          } catch (error) {
            core.setFailed(`❌ Erreur: ${error.message}`);
          }
    
    - name: Trigger jenkinstest run_ci workflow
      id: trigger-workflow-call
      uses: actions/github-script@v7
      continue-on-error: true
      with:
        github-token: ${{ inputs.github-token }}
        script: |
          try {
            core.info('📤 Déclenchement du workflow run_ci sur michelsadeu/jenkinstest');
            
            const target = '${{ steps.parse-ci.outputs.TARGET }}';
            const version = '${{ steps.parse-ci.outputs.VERSION }}';
            const coverage = '${{ steps.parse-ci.outputs.COVERAGE }}';
            const message = `CI triggered with parameters: target=${target}, version=${version}, coverage=${coverage}`;
            
            core.info(`📊 Message: ${message}`);
            
            // Extraire le PR number depuis le contexte
            const prNumber = context.issue.number;
            core.info(`🔢 PR Number: ${prNumber}`);
            
            const dispatchResponse = await github.rest.actions.createWorkflowDispatch({
              owner: 'michelsadeu',
              repo: 'jenkinstest',
              workflow_id: 'run_ci.yml',
              ref: 'main',
              inputs: {
                pr_number: String(prNumber),
                message: message
              }
            });
            
            core.info('✅ run_ci workflow déclenché avec succès');
            core.setOutput('workflow_call_triggered', 'true');
            
          } catch (error) {
            core.warning(`⚠️ Erreur run_ci: ${error.message}`);
            core.warning(`Status: ${error.status}`);
            core.setOutput('workflow_call_triggered', 'false');
          }

    - name: Trigger jenkinstest run_ci workflow (second dispatch)
      id: trigger-workflow-dispatch
      uses: actions/github-script@v7
      continue-on-error: true
      with:
        github-token: ${{ inputs.github-token }}
        script: |
          try {
            core.info('📤 Déclenchement du workflow run_ci (second) sur michelsadeu/jenkinstest');
            
            const target = '${{ steps.parse-ci.outputs.TARGET }}';
            const version = '${{ steps.parse-ci.outputs.VERSION }}';
            const coverage = '${{ steps.parse-ci.outputs.COVERAGE }}';
            const message = `CI triggered with parameters: target=${target}, version=${version}, coverage=${coverage}`;
            
            core.info(`📊 Message: ${message}`);
            
            // Extraire le PR number depuis le contexte
            const prNumber = context.issue.number;
            core.info(`🔢 PR Number: ${prNumber}`);
            
            const dispatchResponse = await github.rest.actions.createWorkflowDispatch({
              owner: 'michelsadeu',
              repo: 'jenkinstest',
              workflow_id: 'run_ci.yml',
              ref: 'main',
              inputs: {
                pr_number: String(prNumber),
                message: message
              }
            });
            
            core.info('✅ run_ci workflow (second) déclenché avec succès');
            core.setOutput('workflow_dispatch_triggered', 'true');
            
          } catch (error) {
            core.warning(`⚠️ Erreur run_ci (second): ${error.message}`);
            core.warning(`Status: ${error.status}`);
            core.setOutput('workflow_dispatch_triggered', 'false');
          }

    - name: Trigger workflow with parsed parameters
      id: trigger-action
      uses: michelsadeu/jenkinstest/.github/workflows/run_ci.yml@main
      with:
        pr_number: ${{ github.event.issue.number }}
        message: "CI triggered with parameters: target=${{ steps.parse-ci.outputs.TARGET }}, version=${{ steps.parse-ci.outputs.VERSION }}, coverage=${{ steps.parse-ci.outputs.COVERAGE }}"

    - name: Trigger workflow with parsed parameters (workflow_call)
      id: trigger-action-call
      uses: michelsadeu/jenkinstest/.github/workflows/run_ci.yml@main
      with:
        pr_number: ${{ github.event.issue.number }}
        message: "CI triggered with parameters: target=${{ steps.parse-ci.outputs.TARGET }}, version=${{ steps.parse-ci.outputs.VERSION }}, coverage=${{ steps.parse-ci.outputs.COVERAGE }}"
